"""LangGraph agent graph for the local-llm API gateway.

Graph flow:
  load_history → call_llm ──(tool calls?)──► run_tools → call_llm (loop)
                           ──(no tools)──► save_reply → generate_title → END

The LLM is a langchain-openai ChatOpenAI client pointed at the local MLX
inference engine's OpenAI-compatible endpoint.
"""

from __future__ import annotations

import logging
import re
from functools import lru_cache

from langchain_core.callbacks.manager import adispatch_custom_event
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langgraph.graph import END, START, StateGraph
from langgraph.prebuilt import ToolNode

from app.agent.state import AgentState
from app.agent.tools.rag import rag_search
from app.agent.tools.web_search import web_search
from app.core.config import get_settings
from app.services.chat_service import ChatService
from app.services.supabase import get_supabase_admin

logger = logging.getLogger(__name__)

TOOLS = [web_search, rag_search]

# Two words, and that is not an oversight. Measured against the live engine at
# temperature 0, on this checkpoint, almost any longer prompt stops it emitting
# tool calls entirely:
#
#   (none)                                  tool-calls 1/2   fenced code 0/2
#   "Be concise."                           tool-calls 1/2   fenced code 2/2
#   "Be concise. Put code in a fenced ..."  tool-calls 0/2   fenced code 2/2
#   "Be concise. Do not invent facts ..."   tool-calls 0/2   fenced code 2/2
#   "You are a coding assistant. ..."       tool-calls 0/2
#
# Two things break it: persona framing ("You are a ... assistant") and any
# instruction about how to shape the answer. Both push the checkpoint into
# explaining rather than acting, and it writes `web_search('...')` as Python
# instead of calling the tool. Bare imperatives survive.
#
# `Be concise.` is strictly better than no prompt at all: same tool-call rate,
# and it produces fenced code blocks the empty prompt does not. Mistral has no
# system role either, so `prompts.py` folds this into the user's first turn --
# every word is charged to their message. Grow this only with measurements.
SYSTEM_PROMPT = "Be concise."

# Titles are generated by the same local checkpoint as the reply — there is no
# second model in this stack, and no hosted one is worth adding for a sidebar
# label. `TITLE_TAG` marks the run so the stream adapter can tell these tokens
# apart from the answer and keep them out of the message body.
TITLE_TAG = "chat-title"
TITLE_MAX_CHARS = 25
TITLE_PROMPT = """Write a short title for a conversation that begins with the \
message below.

Rules: 3 to 5 words. Plain text only. No quotes. No trailing punctuation.

Message: {text}

Title:"""


def _parts_to_text(parts: list[dict] | None) -> str:
    """Extract plain text from AI SDK message parts array."""
    if not parts:
        return ""
    return " ".join(p.get("text", "") for p in parts if p.get("type") == "text")


def _to_langchain_messages(raw: list[dict]) -> list[BaseMessage]:
    """Convert Supabase-stored or wire-format messages to LangChain BaseMessage objects."""
    result: list[BaseMessage] = []
    for m in raw:
        role = m.get("role", "user")
        # Support both direct content string and AI SDK parts array
        content = m.get("content") or _parts_to_text(m.get("parts"))
        if not content:
            continue
        if role == "user":
            result.append(HumanMessage(content=content))
        elif role == "assistant":
            result.append(AIMessage(content=content))
        elif role == "system":
            result.append(SystemMessage(content=content))
    return result


# ─── Nodes ────────────────────────────────────────────────────────────────────


def _clean_title(raw: str) -> str:
    """Coerce model output into something that fits a sidebar row.

    Mamba-Codestral is a base code model, not instruction-tuned, so it answers
    a "write a title" prompt with whatever it likes — a sentence, a restatement
    of the prompt, a code fence. Everything here is damage control; the caller
    keeps a deterministic fallback for when there is nothing usable left.
    """
    text = (raw or "").strip()
    if not text:
        return ""

    # First non-empty line: the model often continues past the title.
    line = next((ln.strip() for ln in text.splitlines() if ln.strip()), "")
    line = re.sub(r"^(title|chat title)\s*[:\-]\s*", "", line, flags=re.IGNORECASE)
    line = line.strip(" \t\"'`*#_")
    line = re.sub(r"\s+", " ", line)

    if len(line) > TITLE_MAX_CHARS:
        line = line[:TITLE_MAX_CHARS].rsplit(" ", 1)[0]

    return line.rstrip(" .,:;-").strip()


def _fallback_title(source: str) -> str:
    """Derive a title from the user's own words. Never empty for real input."""
    text = re.sub(r"\s+", " ", (source or "").strip())
    if not text:
        return "New chat"
    if len(text) > TITLE_MAX_CHARS:
        text = text[:TITLE_MAX_CHARS].rsplit(" ", 1)[0]
    return text.rstrip(" .,:;-").strip() or "New chat"


def load_history(state: AgentState) -> dict:
    """Fetch prior chat messages from Supabase and prepend them to state."""
    chat_id = state["chat_id"]
    supabase = get_supabase_admin()

    res = (
        supabase.table("messages")
        .select("*")
        .eq("chat_id", chat_id)
        .order("created_at")
        .execute()
    )
    history_rows = res.data or []

    # The router persists the current user turn before invoking the graph, so
    # the DB rows are the whole conversation including this turn. state
    # ["messages"] is empty unless that write failed.
    history = _to_langchain_messages(history_rows)

    # Read the title here rather than in the title node: this is the one place
    # already paying for a round trip, and an empty title is the only signal
    # that distinguishes "never named" from "named, possibly by hand".
    needs_title = not ChatService.get_title(chat_id).strip()

    logger.debug("load_history: %d messages for chat %s", len(history), chat_id)
    return {"messages": history, "needs_title": needs_title}


def save_reply(state: AgentState) -> dict:
    """Persist the last AI message to Supabase after generation completes."""
    messages = state.get("messages", [])
    # Find last AIMessage
    ai_msgs = [m for m in messages if isinstance(m, AIMessage)]
    if not ai_msgs:
        return {}

    last_ai = ai_msgs[-1]
    if not last_ai.content:
        return {}

    ChatService.save_message(
        chat_id=state["chat_id"],
        role="assistant",
        parts=[{"type": "text", "text": last_ai.content}],
        # Same id the client is rendering under, so a vote or an edit issued
        # right after the stream resolves against a row that exists.
        message_id=state.get("assistant_message_id"),
    )
    return {}


async def generate_title(state: AgentState) -> dict:
    """Name the chat from its opening message, once, after the reply is done.

    Runs last on purpose. The engine serializes generation onto a single worker
    (ADR 0003), so titling concurrently with the answer would either queue
    behind it or be shed as load — either way the user waits longer for the
    first token. Here it costs nothing the user is watching.
    """
    if not state.get("needs_title"):
        return {}

    first_user = next(
        (m for m in state.get("messages", []) if isinstance(m, HumanMessage)), None
    )
    if first_user is None:
        return {}

    source = str(first_user.content)
    title = _fallback_title(source)

    try:
        response = await _title_llm(state.get("model") or "").ainvoke(
            [HumanMessage(content=TITLE_PROMPT.format(text=source))]
        )
        title = _clean_title(str(getattr(response, "content", ""))) or title
    except Exception as e:  # noqa: BLE001
        # The reply already streamed; a missing title is not worth failing over.
        logger.warning("title generation failed for chat %s: %s", state["chat_id"], e)

    ChatService.set_title(state["chat_id"], title)

    # Reaches the browser as a transient data part — the sidebar and header
    # update without the client refetching to discover what changed.
    await adispatch_custom_event("chat_title", {"title": title})
    return {}


def should_use_tools(state: AgentState) -> str:
    """Route: if the last AI message has tool calls, run them; otherwise finish."""
    messages = state.get("messages", [])
    if not messages:
        return END
    last = messages[-1]
    if isinstance(last, AIMessage) and last.tool_calls:
        return "run_tools"
    return "save_reply"


# ─── Graph ────────────────────────────────────────────────────────────────────


def _build_llm(model: str) -> ChatOpenAI:
    """Construct a ChatOpenAI client pointing at the local MLX engine."""
    settings = get_settings()
    return ChatOpenAI(
        model=model or settings.model_id,
        base_url=f"{settings.llm_engine_url}/v1",
        api_key="not-used",  # MLX engine has no key requirement
        streaming=True,
        temperature=0.7,
        max_completion_tokens=settings.max_tokens,
    ).bind_tools(TOOLS)


@lru_cache(maxsize=4)
def _cached_llm(model: str) -> ChatOpenAI:
    return _build_llm(model)


@lru_cache(maxsize=4)
def _title_llm(model: str):
    """The same engine, without tools and on a short leash.

    Tools are omitted deliberately: a title is a one-shot label, and binding
    them only invites a tool call the checkpoint cannot make anyway.
    """
    settings = get_settings()
    return ChatOpenAI(
        model=model or settings.model_id,
        base_url=f"{settings.llm_engine_url}/v1",
        api_key="not-used",
        streaming=False,
        temperature=0.2,
        max_completion_tokens=24,
    ).with_config({"tags": [TITLE_TAG], "run_name": "generate_title"})


def build_graph(model: str = "") -> StateGraph:
    """Build and compile the LangGraph StateGraph.

    Returns a compiled graph that accepts AgentState and streams events.
    """
    settings = get_settings()
    llm = _cached_llm(model or settings.model_id)

    def call_llm(state: AgentState) -> dict:
        system = SystemMessage(content=SYSTEM_PROMPT)
        response = llm.invoke([system, *state["messages"]])
        return {"messages": [response]}

    tool_node = ToolNode(TOOLS)

    graph = StateGraph(AgentState)

    graph.add_node("load_history", load_history)
    graph.add_node("call_llm", call_llm)
    graph.add_node("run_tools", tool_node)
    graph.add_node("save_reply", save_reply)
    graph.add_node("generate_title", generate_title)

    graph.add_edge(START, "load_history")
    graph.add_edge("load_history", "call_llm")
    graph.add_conditional_edges(
        "call_llm", should_use_tools, ["run_tools", "save_reply"]
    )
    graph.add_edge("run_tools", "call_llm")  # loop back after tool results
    graph.add_edge("save_reply", "generate_title")
    graph.add_edge("generate_title", END)

    return graph.compile()
